### ISSUE TITLE
encountered  a IOError when using mimir

### ISSUE THREAD

**Issue by waghhhhh** [bartvm/mimir#9]
I guess I‘ve installed mimir correctly,like this:

adding 'mimir/__init__.py'
adding 'mimir/formatters.py'
adding 'mimir/gzlog.so'
adding 'mimir/handlers.py'
adding 'mimir/logger.py'
adding 'mimir/plot.py'
adding 'mimir/remote.py'
adding 'mimir/serialization.py'
adding 'mimir/stream.py'
adding 'mimir/utils.py'
adding 'mimir-0.1.dev1.dist-info/LICENSE'
adding 'mimir-0.1.dev1.dist-info/METADATA'
adding 'mimir-0.1.dev1.dist-info/WHEEL'
adding 'mimir-0.1.dev1.dist-info/top_level.txt'
adding 'mimir-0.1.dev1.dist-info/RECORD'
removing build/bdist.linux-x86_64/wheel

and I have ran the .whl file
but when I use mimir to run a program, it goes wrong

 File "/home/mrbing/anaconda3/envs/keras_theano/lib/python2.7/site-packages/mimir/logger.py", line 71, in Logger
    handlers.append(GzipJSONHandler(root))
  File "/home/mrbing/anaconda3/envs/keras_theano/lib/python2.7/site-packages/mimir/handlers.py", line 134, in __init__
    stream = gzlog.GZipLog(filename)
  File "gzlog/gzlog.pyx", line 89, in mimir.gzlog.GZipLog.__init__
  File "gzlog/gzlog.pyx", line 26, in mimir.gzlog.Gzlog.__cinit__
IOError

I dont kown why this happens, can u give me some suggestions?
Thx a lot

**Comment by bartvm** [comment]
This happens if `gzlog_open` failed for whatever reason. Sadly `zlib` doesn't give any more details. 

Some things to check: Did you pass a filename? Do you have write access to this directory? Did you run out of disk space? Are you trying to write a zipped log to a file that already exists?

Good luck!
